name: Release

on:
  release:
    types: [published]

jobs:

  build:
    name: Build release binaries
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Build linux/amd64
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -v -o traefik-forward-auth_amd64 ./cmd

    - name: Build linux/arm
      run: CGO_ENABLED=0 GOOS=linux GOARCH=arm GO111MODULE=on go build -v -o traefik-forward-auth_arm ./cmd

    - name: Get tag name
      run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Get artifact details
      uses: octokit/request-action@v2.x
      id: get_release_details
      with:
        route: get /repos/${{ github.repository }}/releases/tags/${{ env.TAG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload linux/amd64 release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ fromJson(steps.get_release_details.outputs.data).upload_url }}
        asset_path: traefik-forward-auth_amd64
        asset_name: traefik-forward-auth_amd64
        asset_content_type: application/octet-stream

    - name: Upload linux/arm release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ fromJson(steps.get_release_details.outputs.data).upload_url }}
        asset_path: traefik-forward-auth_arm
        asset_name: traefik-forward-auth_arm
        asset_content_type: application/octet-stream
